# Generated by Django 4.2 on 2023-04-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShaharTuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255, verbose_name={'sh': 'Shaxar', 't': 'Shaxar'})),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(default='Malumot yoq')),
                ('sh_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shahartuman')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masjid/')),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masjid')),
            ],
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.masjid')),
            ],
        ),
    ]
