# Generated by Django 4.2 on 2023-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hodim_status_alter_shahartuman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='status',
            field=models.IntegerField(choices=[(1, 'Imom'), (4, 'Muazzin'), (2, 'Imom hatib'), (3, 'Qori')]),
        ),
        migrations.AlterField(
            model_name='shahartuman',
            name='status',
            field=models.CharField(choices=[('t', 'Shaxar'), ('sh', 'Shaxar')], max_length=255),
        ),
    ]
