# Generated by Django 4.2 on 2023-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hodim_status_alter_shahartuman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shahartuman',
            name='status',
            field=models.CharField(choices=[('Shaxar', 'Shaxar'), ('Tuman', 'Tuman')], max_length=255),
        ),
    ]
