# Generated by Django 4.2 on 2023-05-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_hodim_status_alter_image_masjid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='status',
            field=models.CharField(choices=[('Muazzin', 'Muazzin'), ('Qori', 'Qori'), ('Imom', 'Imom'), ('Imom hatib', 'Imom hatib')], max_length=255),
        ),
        migrations.CreateModel(
            name='HodimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hodim/')),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.hodim')),
            ],
        ),
    ]
