# Generated by Django 4.2 on 2023-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_hodim_status_hodimimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='status',
            field=models.CharField(choices=[('Qori', 'Qori'), ('Imom', 'Imom'), ('Imom hatib', 'Imom hatib'), ('Muazzin', 'Muazzin')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shahartuman',
            name='status',
            field=models.CharField(choices=[('Shaxar', 'Shaxar'), ('Tuman', 'Tuman')], max_length=255),
        ),
    ]
