# Generated by Django 4.2 on 2023-05-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_hodim_status_alter_shahartuman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='about',
            field=models.TextField(default='Malumot yoq'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='masjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masjidi', to='main.masjid'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='status',
            field=models.CharField(choices=[('Qori', 'Qori'), ('Imom hatib', 'Imom hatib'), ('Muazzin', 'Muazzin'), ('Imom', 'Imom')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shahartuman',
            name='status',
            field=models.CharField(choices=[('Tuman', 'Tuman'), ('Shaxar', 'Shaxar')], max_length=255),
        ),
    ]
